/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p kwineffects_interface /home/peter/.local/src/public-repos/LightlyShaders/org.kde.kwin.Effects.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "kwineffects_interface.h"

/*
 * Implementation of interface class OrgKdeKwinEffectsInterface
 */

OrgKdeKwinEffectsInterface::OrgKdeKwinEffectsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeKwinEffectsInterface::~OrgKdeKwinEffectsInterface()
{
}


#include "kwineffects_interface.moc"
